events {}

http {

    upstream user_service {
        server user-nginx:80;
    }

    upstream order_service {
        server order-nginx:80;
    }

    server {
        listen 80;

        location /users/ {

            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /orders/ {

            proxy_pass http://order_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # location / {
        #     return 200 "API Gateway Running";
        # }

        error_page 502 503 504 /custom-50x.json;

        location = /custom-50x.json {
            internal;
            return 500 '{"error":"Service unavailable","status":500}';
        }
    }
}
