events {}

http {

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    upstream user_service {
        server user-service:8000;
    }

    upstream order_service {
        server order-service:8000;
    }

    server {
        listen 80;

        # USER SERVICE
        location /api/users/ {
            rewrite ^/api/users/?(.*)$ /api/$1 break;
            proxy_pass http://user_service/;
            proxy_intercept_errors on;
        }

        # ORDER SERVICE
        location /api/orders/ {
            rewrite ^/api/orders/?(.*)$ /api/$1 break;
            proxy_pass http://order_service/;
            proxy_intercept_errors on;
        }

        # Optional: health check
        location / {
            return 200 "API Gateway Running";
        }

        # 👇 custom error page mapping
        error_page 404 /custom-404.json;

        location = /custom-404.json {
            internal;
            default_type application/json;
            return 404 '{"error":"Route not found","status":404}';
        }


        error_page 502 503 504 /custom-50x.json;

        location = /custom-50x.json {
            internal;
            default_type application/json;
            return 500 '{"error":"Service unavailable","status":500}';
        }
    }
}